feat: initial uds postgres operator with optional database deployment chart
defenseunicorns/uds-package-postgres-operator pull request #2
Opened 2024-02-28 04:03 UTC by zachariahmiller

WIP: Missing CI, doc updates and registry1 testing

2024-02-29 16:44 UTC, Racer159 requested changes
Mostly just comments with a few changes / cleanups

2024-02-29 16:44 UTC, Racer159 commented on renovate.json
> +      }
These are not in the README anymore.

2024-02-29 16:44 UTC, Racer159 commented on .github/workflows/scorecard.yaml
> +          repo_token: ${{ secrets.SCORECARD_READ_TOKEN }}
This isn't _required_ for this to run but it will be more limited when non-existent - we don't have to fix this now (pretty sure this is an issue in other repos too) but likely worth a `tech-debt` issue

2024-02-29 16:44 UTC, Racer159 commented on tasks/publish.yaml
> +          ZARF_ARCHITECTURE=arm64 uds run -f tasks/create.yaml postgres-operator --no-progress --set FLAVOR=${FLAVOR}
```suggestion
          uds run -a amd64 -f tasks/create.yaml postgres-operator --no-progress --set FLAVOR=${FLAVOR}
          uds run -a arm64 -f tasks/create.yaml postgres-operator --no-progress --set FLAVOR=${FLAVOR}
```
Can we do this instead?

2024-02-29 16:44 UTC, Racer159 commented on chart/templates/peer-auth-exception.yaml
> +      mode: PERMISSIVE
Just a note that is more likely a `tech-debt` issue - while spilo does make TLS certs on its own and protects against simply sniffing the wire, the cert is not verifiable by clients and could still be subject to MITM.

https://opensource.zalando.com/postgres-operator/docs/user.html#custom-tls-certificates

2024-02-29 16:49 UTC, zachariahmiller commented on CODEOWNERS
> +/* @defenseunicorns/uds
i dont have access to the repo setting i reached out to @oates to help with that

2024-02-29 16:50 UTC, zachariahmiller commented on chart/templates/peer-auth-exception.yaml
> +      mode: PERMISSIVE
Will create a followup issue for this.

2024-02-29 16:52 UTC, zachariahmiller commented on tasks/publish.yaml
> +          ZARF_ARCHITECTURE=arm64 uds run -f tasks/create.yaml postgres-operator --no-progress --set FLAVOR=${FLAVOR}
This is how we're doing it everywhere else currrently:
https://github.com/defenseunicorns/uds-core/blob/main/tasks/publish.yaml
https://github.com/defenseunicorns/uds-package-gitlab/blob/42e1f96de45381d514ff475715a3f7d301c24c37/tasks/publish.yaml

My aim was for consistency and I would prefer not to diverge unless we can document how we want to do this across uds repos and change it across them

2024-02-29 16:54 UTC, zachariahmiller commented on README.md
> +| deploy-package | Deploy Postgres Operator package only | `uds run deploy-package` |
oof `deploy-package` specifically right? i guess i missed that one when i was running through this list to check

2024-02-29 16:55 UTC, zachariahmiller commented on .github/workflows/commitlint.yaml
> +    uses: defenseunicorns/uds-common/.github/workflows/commitlint.yaml@417b9c2bc088f664c616c9929a2b3ce448d251f7
Will create a follow up issue to add yaml linting to the repository

2024-02-29 16:57 UTC, zachariahmiller commented on README.md
> +| deploy-package | Deploy Postgres Operator package only | `uds run deploy-package` |
i like you suggestion. I was basing the readme off another repo for consistency.

2024-02-29 17:14 UTC, zachariahmiller commented on renovate.json
> +      }
uds-cli is 
![image](https://github.com/defenseunicorns/uds-package-postgres-operator/assets/71521611/177e885f-07a1-4c54-9673-c54182fa9ec0)

I expected to have to add back uds core (istio), but will remove and update when its actually there

2024-02-29 17:45 UTC, zachariahmiller commented on CODEOWNERS
> +/* @defenseunicorns/uds
fixed

2024-02-29 17:46 UTC, zachariahmiller commented on README.md
> +| deploy-package | Deploy Postgres Operator package only | `uds run deploy-package` |
replaced with above suggestion

2024-02-29 17:57 UTC, zachariahmiller commented on .github/workflows/commitlint.yaml
> +    uses: defenseunicorns/uds-common/.github/workflows/commitlint.yaml@417b9c2bc088f664c616c9929a2b3ce448d251f7
actually just added the yaml lint checks we use in the other uds repos and remediated findings

2024-02-29 17:58 UTC, zachariahmiller commented on .github/workflows/scorecard.yaml
> +          repo_token: ${{ secrets.SCORECARD_READ_TOKEN }}
will create an issue but we need to detach the fork first

2024-02-29 17:59 UTC, zachariahmiller commented on chart/templates/peer-auth-exception.yaml
> +      mode: PERMISSIVE
Same comment on this... made a note to create an issue but the fork needs to be detached (wish it hadn't been forked 😢 )

2024-02-29 20:07 UTC, ericwyles commented on tasks/test.yaml
> +        cmd: "./zarf package deploy ../build/zarf-package-postgres-test-* --confirm"
question: Should this be 'uds zarf' or is './zarf' ok in this context?

2024-02-29 22:13 UTC, zachariahmiller commented on renovate.json
> +      }
i removed them.

2024-02-29 22:13 UTC, zachariahmiller commented on tasks/test.yaml
> +        cmd: "./zarf package deploy ../build/zarf-package-postgres-test-* --confirm"
Good catch @ericwyles thanks!

2024-02-29 22:14 UTC, zachariahmiller commented on tasks/test.yaml
> +        cmd: "./zarf package deploy ../build/zarf-package-postgres-test-* --confirm"
fixed

2024-03-01 00:01 UTC, zachariahmiller commented
@Racer159 tagging for another review

2024-03-01 14:44 UTC, MxNxPx approved these changes
lgtm!

2024-03-01 14:51 UTC, TristanHoladay approved these changes

2024-03-01 17:15 UTC, mjnagel commented on chart/templates/uds-package.yaml
> +      {{ .Values.postgresql.ingress | toYaml | indent 4 }}
```suggestion
        {{- .Values.postgresql.ingress | toYaml | nindent 6 }}
```
I think

2024-03-01 17:16 UTC, zachariahmiller commented on chart/templates/uds-package.yaml
> +      {{ .Values.postgresql.ingress | toYaml | indent 4 }}
lol thank you!

2024-03-01 19:48 UTC, Racer159 approved these changes
lgtm

2024-03-01 20:44 UTC, zachariahmiller commented
Blocked by registry1 outage

2024-03-02 00:03 UTC, merged